# Generated by Django 4.2.2 on 2024-09-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_payments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_pay',
            field=models.DateField(auto_now_add=True, verbose_name='Дата оплаты'),
        ),
    ]
