# Generated by Django 4.2.2 on 2024-10-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payments_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="way",
        ),
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Id сессии"
            ),
        ),
    ]
