# Generated by Django 4.2.2 on 2024-10-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_payments_amount_remove_payments_way_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="amount",
            field=models.IntegerField(default=0, verbose_name="сумма оплаты"),
        ),
    ]
