# Generated by Django 4.2.2 on 2024-09-22 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_alter_subscription_options_subscription_exists"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="exists",
        ),
    ]
