# Generated by Django 4.2.2 on 2024-10-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0005_remove_subscription_exists"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.IntegerField(default=100000, verbose_name="цена"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.IntegerField(default=10000, verbose_name="цена"),
        ),
    ]
