# Generated by Django 4.2.2 on 2024-10-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0006_course_price_lesson_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(
                default="Создан", max_length=25, verbose_name="статус"
            ),
        ),
    ]
